customer_list:
  path: /api/v1/customers
  controller: App\Controller\CustomerController::indexAction
  methods: [GET]

customer_create:
  path: /api/v1/customers/create
  controller: App\Controller\CustomerController::createAction
  methods: [POST]

customer_edit:
  path: /api/v1/customers/edit/{id}
  controller: App\Controller\CustomerController::editAction
  methods: [PUT]

customer_delete:
  path: /api/v1/customers/delete/{id}
  controller: App\Controller\CustomerController::deleteAction
  methods: [DELETE]
